version: '3.5'

services:
  dev-db:
    container_name: nestjs-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestjs-db
    volumes:
      - postgres-db:/data/postgres
    ports:
      - '5432:5432'

  test-db:
    container_name: nestjs-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestjs-db
    volumes:
      - postgres-db:/data/postgres
    ports:
      - '5435:5432'

volumes:
  postgres-db:
    driver: local
